export const DefaultButtonsData =  [
    {
        id: "power",
        name: "power",
        value: "ON",
        disabled: false,
        type: "button",
    },
    {
        id: "percentage",
        name: "percentage",
        value: "%",
        disabled: true,
        type: "button",
    },
    {
        id: "sqrt",
        name: "square",
        value: '\u{221A}',
        disabled: true,
        type: "button",
    },
    {
        id: "backspace",
        name: "backspace",
        value: '\u{232B}',
        disabled: true,
        type: "button",
    },
    {
        id: "mrc",
        name: "memory-clear",
        value: "MRC",
        disabled: true,
        type: "button",
    },
    {
        id: "msub",
        name: "memory-substract",
        value: "M-",
        disabled: true,
        type: "button",
    },
    {
        id: "madd",
        name: "memory-add",
        value: "M+",
        disabled: true,
        type: "button",
    },
    {
        id: "clear",
        name: "clear",
        value: '\u{24E7}',
        disabled: true,
        type: "button",
    },
    {
        id: "devide",
        name: "devide",
        value: '\u{00F7}',
        disabled: true,
        type: "button",
    },
    {
        id: "multiply",
        name: "multiply",
        value: '\u{00D7}',
        disabled: true,
        type: "button",
    },
    {
        id: "add",
        name: "add",
        value: "+",
        disabled: true,
        type: "button",
    },
    {
        id: "subtract",
        name: "subtract",
        value: '-',
        disabled: true,
        type: "button",
    },
    {
        id: "decimal",
        name: "decimal",
        value: ".",
        disabled: true,
        type: "button",
    },
    {
        id: "zero",
        name: "zero",
        value: "0",
        disabled: true,
        type: "button",
    },
    {
        id: "one",
        name: "one",
        value: "1",
        disabled: true,
        type: "button",
    },
    {
        id: "two",
        name: "two",
        value: "2",
        disabled: true,
        type: "button",
    },
    {
        id: "three",
        name: "three",
        value: "3",
        disabled: true,
        type: "button",
    },
    {
        id: "four",
        name: "four",
        value: "4",
        disabled: true,
        type: "button",
    },
    {
        id: "five",
        name: "five",
        value: "5",
        disabled: true,
        type: "button",
    },
    {
        id: "six",
        name: "six",
        value: "6",
        disabled: true,
        type: "button",
    },
    {
        id: "seven",
        name: "seven",
        value: "7",
        disabled: true,
        type: "button",
    },
    {
        id: "eight",
        name: "eight",
        value: "8",
        disabled: true,
        type: "button",
    },
    {
        id: "nine",
        name: "nine",
        value: "9",
        disabled: true,
        type: "button",
    },
    {
        id: "equal",
        name: "equal",
        value: "=",
        disabled: true,
        type: "button",
    },
    
 ]