export const DefaultButtonsData =  [
    {
        id: "power",
        name: "power",
        value: "ON",
        type: "button",
    },
    {
        id: "percentage",
        name: "percentage",
        value: "%",
        type: "button",
    },
    {
        id: "sqrt",
        name: "square",
        value: '\u{221A}',
        type: "button",
    },
    {
        id: "backspace",
        name: "backspace",
        value: '\u{232B}',
        type: "button",
    },
    {
        id: "mrc",
        name: "memory-clear",
        value: "MRC",
        type: "button",
    },
    {
        id: "msub",
        name: "memory-substract",
        value: "M-",
        type: "button",
    },
    {
        id: "madd",
        name: "memory-add",
        value: "M+",
        type: "button",
    },
    {
        id: "clear",
        name: "clear",
        value: '\u{24E7}',
        type: "button",
    },
    {
        id: "divide",
        name: "divide",
        value: '\u{00F7}',
        type: "button",
    },
    {
        id: "multiply",
        name: "multiply",
        value: '\u{00D7}',
        type: "button",
    },
    {
        id: "add",
        name: "add",
        value: "+",
        type: "button",
    },
    {
        id: "subtract",
        name: "subtract",
        value: '-',
        type: "button",
    },
    {
        id: "decimal",
        name: "decimal",
        value: ".",
        type: "button",
    },
    {
        id: "zero",
        name: "zero",
        value: "0",
        type: "button",
    },
    {
        id: "one",
        name: "one",
        value: "1",
        type: "button",
    },
    {
        id: "two",
        name: "two",
        value: "2",
        type: "button",
    },
    {
        id: "three",
        name: "three",
        value: "3",
        type: "button",
    },
    {
        id: "four",
        name: "four",
        value: "4",
        type: "button",
    },
    {
        id: "five",
        name: "five",
        value: "5",
        type: "button",
    },
    {
        id: "six",
        name: "six",
        value: "6",
        type: "button",
    },
    {
        id: "seven",
        name: "seven",
        value: "7",
        type: "button",
    },
    {
        id: "eight",
        name: "eight",
        value: "8",
        type: "button",
    },
    {
        id: "nine",
        name: "nine",
        value: "9",
        type: "button",
    },
    {
        id: "equals",
        name: "equal",
        value: "=",
        type: "button",
    },
    
 ]